name: Automated Test

on: [push]

jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Produce Test 1 Output
      run: python find_lowest_number.py test_data/test1_input.txt test_data/output1.txt

    - name: Test 1
      run: diff test_data/output1.txt test_data/test1_expected.txt

    - name: Produce Test 2 Output
      run: python find_lowest_number.py test_data/test2_input.txt test_data/output2.txt

    - name: Test 2
      run: diff test_data/output2.txt test_data/test2_expected.txt

    - name: Produce Test 3 Output
      run: python find_lowest_number.py test_data/test3_input.txt test_data/output3.txt

    - name: Test 3
      run: diff test_data/output3.txt test_data/test3_expected.txt
